### ISSUE TITLE
模型可接受的输入的最大分辨率是多少？

### ISSUE THREAD

**Issue by Cynicarlos** [Yaziwel/Restore-RWKV#10]
如题，对于高分辨率图像，例如2K*2K的图像是否可行？训练时可以裁剪成512*512的，但推理时一般是原图输入的，请问该怎么办？这算不算是该模型的不足？

**Comment by Yaziwel** [comment]
> 如题，对于高分辨率图像，例如2K_2K的图像是否可行？训练时可以裁剪成512_512的，但推理时一般是原图输入的，请问该怎么办？这算不算是该模型的不足？

模型可接受的最大输入分辨率与算力有关，2k×2k这个分辨率可能确实偏大。你可以在推理时使用with torch.no_grad()，试一下在你的显卡下能推理多大分辨率的图像。
